# Generated by Django 4.2 on 2026-06-09 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_images'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('F', 'Fuego'), ('T', 'Tierra'), ('A', 'Agua'), ('E', 'Electrico'), ('P', 'Planta')], max_length=50),
        ),
    ]
